-- =========================================
-- Sales Data Analysis Project
-- Tables:
-- CLIENTES, PRODUCTOS, VENTAS, EMPLEADOS, CATEGORIAS, DETALLE_VENTA
-- =========================================

-- 1. Total Revenue
SELECT
    SUM(TOTAL) AS TOTAL_REVENUE
FROM VENTAS;

-- 2. Total Orders
SELECT
    COUNT(*) AS TOTAL_ORDERS
FROM VENTAS;

-- 3. Best Selling Products
SELECT
    P.NOMBRE,
    SUM(DV.CANTIDAD) AS UNITS_SOLD,
    SUM(DV.SUBTOTAL) AS REVENUE
FROM DETALLE_VENTA DV
JOIN PRODUCTOS P
    ON DV.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY P.NOMBRE
ORDER BY REVENUE DESC;

-- 4. Revenue By Category
SELECT
    C.NOMBRE_CATEGORIA,
    SUM(DV.SUBTOTAL) AS REVENUE
FROM DETALLE_VENTA DV
JOIN PRODUCTOS P
    ON DV.ID_PRODUCTO = P.ID_PRODUCTO
JOIN CATEGORIAS C
    ON P.ID_CATEGORIA = C.ID_CATEGORIA
GROUP BY C.NOMBRE_CATEGORIA
ORDER BY REVENUE DESC;

-- 5. Top Customers
SELECT
    CL.NOMBRE,
    SUM(V.TOTAL) AS TOTAL_SPENT
FROM CLIENTES CL
JOIN VENTAS V
    ON CL.ID_CLIENTE = V.ID_CLIENTE
GROUP BY CL.NOMBRE
ORDER BY TOTAL_SPENT DESC;

-- 6. Sales By Employee
SELECT
    E.NOMBRE,
    SUM(V.TOTAL) AS TOTAL_SALES
FROM EMPLEADOS E
JOIN VENTAS V
    ON E.ID_EMPLEADO = V.ID_EMPLEADO
GROUP BY E.NOMBRE
ORDER BY TOTAL_SALES DESC;
